@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]] {
        +gameObject: GameObject
        +start(): void
        +update(float): void
        +imgui(): void
        +generateID(): void
        +getGameObject(): GameObject
        +setGameObject(GameObject): void
        {static} +getID_COUNTER(): int
        {static} +setID_COUNTER(int): void
        +getUid(): int
        {static} +init(int): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
