@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Gizmo\n<size:10>game.components" as game.components.Gizmo [[Gizmo.html]] {
        #activeGameObject: GameObject
        #xAxisActive: boolean
        #yAxisActive: boolean
        +Gizmo(Sprite, PropertiesWindow)
        +start(): void
        +update(float): void
        +editorUpdate(float): void
        +setActive(): void
        +setInactive(): void
        +setUsing(): void
        +setNotUsing(): void
    }

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]]

    game.components.Component <|-- game.components.Gizmo

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
