@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>Interaktive\n<size:10>game.components" as game.components.Interaktive [[Interaktive.html]] {
        {abstract} +interact(GameObject): void
        +setInteractive(boolean): void
        +getInteractive(): boolean
        +update(float): void
    }

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]]

    game.components.Component <|-- game.components.Interaktive

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
