@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>InteraktiveGizmo\n<size:10>game.components" as game.components.InteraktiveGizmo [[InteraktiveGizmo.html]] {
        +InteraktiveGizmo(Sprite)
        +update(float): void
    }

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]]

    game.components.Component <|-- game.components.InteraktiveGizmo

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
