@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KeyControls\n<size:10>game.components" as game.components.KeyControls [[KeyControls.html]] {
        +editorUpdate(float): void
        {static} +rotateGOs90Deg(List<GameObject>): void
    }

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]]

    game.components.Component <|-- game.components.KeyControls

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
