@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PlayerController\n<size:10>game.components" as game.components.PlayerController [[PlayerController.html]] {
        +walkSpeed: float
        +slowDownForc: float
        +terminalVelocity: Vector2f
        +start(): void
        +update(float): void
    }

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]]

    game.components.Component <|-- game.components.PlayerController

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
