@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ScaleGizmo\n<size:10>game.components" as game.components.ScaleGizmo [[ScaleGizmo.html]] {
        +ScaleGizmo(Sprite, PropertiesWindow)
        +editorUpdate(float): void
    }

    class "<size:14>Gizmo\n<size:10>game.components" as game.components.Gizmo [[Gizmo.html]]

    game.components.Gizmo <|-- game.components.ScaleGizmo

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
