@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TranslateGizmo\n<size:10>game.components" as game.components.TranslateGizmo [[TranslateGizmo.html]] {
        +TranslateGizmo(Sprite, PropertiesWindow)
        +start(): void
        +update(float): void
        +setActive(): void
        +setInactive(): void
    }

    abstract class "<size:14>Component\n<size:10>game.components" as game.components.Component [[Component.html]]

    game.components.Component <|-- game.components.TranslateGizmo

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
