/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import game.engine.Window;

public class App {

    public static void main(String[] args) {
		Window window = Window.get();
		window.run();
    }
}
