@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>CameraModi\n<size:10>game.components.enums" as game.components.enums.CameraModi [[CameraModi.html]] {
        {static} +FOLLOWING
        {static} +STATIC
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
