@startuml
    namespace game.components.enums {

        enum BodyType [[BodyType.html]] {
            {static} +Static
            {static} +Dynamic
            {static} +Kinematic
        }

        enum CameraModi [[CameraModi.html]] {
            {static} +FOLLOWING
            {static} +STATIC
        }

    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
