@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PickingTexture\n<size:10>game.renderer" as game.renderer.PickingTexture [[PickingTexture.html]] {
        +PickingTexture(int, int)
        +init(int, int): boolean
        +enableWriting(): void
        +disableWriting(): void
        +readPixel(int, int): int
        +readPixels(Vector2i, Vector2i): float[]
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
