@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Renderer\n<size:10>game.renderer" as game.renderer.Renderer [[Renderer.html]] {
        +add(GameObject): void
        {static} +bindShader(Shader): void
        {static} +getBoundShader(): Shader
        +render(): void
        +destroyGameObject(GameObject): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
