@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LevelEditorSceneInitializer\n<size:10>game.scene" as game.scene.LevelEditorSceneInitializer [[LevelEditorSceneInitializer.html]] {
        +init(Scene): void
        +loadResources(Scene): void
        +imgui(): void
        +ImGuiWordSet(): void
    }

    abstract class "<size:14>SceneInitializer\n<size:10>game.scene" as game.scene.SceneInitializer [[SceneInitializer.html]] {
        {abstract} +init(Scene): void
        {abstract} +loadResources(Scene): void
        {abstract} +imgui(): void
    }

    game.scene.SceneInitializer <|-- game.scene.LevelEditorSceneInitializer

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
