@startuml
    namespace game.scene {

        class LevelEditorScene [[LevelEditorScene.html]] {
            +init(): void
            +update(float): void
            +render(): void
            +imgui(): void
            +ImGuiWordSet(): void
        }

        class LevelScene [[LevelScene.html]] {
            +update(float): void
            +render(): void
            +init(): void
        }

        abstract class Scene [[Scene.html]] {
            #renderer: Renderer
            #camera: Camera
            #loadedLevel: boolean
            #gameObjects: List<GameObject>
            +init(): void
            +start(): void
            +addGameObject(GameObject): void
            {abstract} +update(float): void
            {abstract} +render(): void
            +camera(): Camera
            +getGameObjectWith(Class<T extends Component>): GameObject
            +getGameObjects(): List<GameObject>
            +getGameObject(int): GameObject
            +imgui(): void
            +saveExit(): void
            +load(): void
        }

        Scene <|-- LevelEditorScene
        Scene <|-- LevelScene
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
