@startuml
    namespace game.scene {

        class LevelEditorSceneInitializer [[LevelEditorSceneInitializer.html]] {
            +init(Scene): void
            +loadResources(Scene): void
            +imgui(): void
            +ImGuiWordSet(): void
        }

        class Scene [[Scene.html]] {
            #gameObjects: List<GameObject>
            +Scene(SceneInitializer)
            +init(): void
            +start(): void
            +addGameObject(GameObject): void
            +editorUpdate(float): void
            +update(float): void
            +render(): void
            +camera(): Camera
            +getGameObjectWith(Class<T extends Component>): GameObject
            +getGameObjects(): List<GameObject>
            +getGameObject(int): GameObject
            +imgui(): void
            +createGameObject(String): GameObject
            +save(): void
            +load(): void
            +destroy(): void
        }

        abstract class SceneInitializer [[SceneInitializer.html]] {
            {abstract} +init(Scene): void
            {abstract} +loadResources(Scene): void
            {abstract} +imgui(): void
        }

        SceneInitializer <|-- LevelEditorSceneInitializer
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
