@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Scene\n<size:10>game.scene" as game.scene.Scene [[Scene.html]] {
        #gameObjects: List<GameObject>
        +Scene(SceneInitializer)
        +init(): void
        +start(): void
        +gameStart(): void
        +addGameObject(GameObject): void
        +editorUpdate(float): void
        +update(float): void
        +render(): void
        +camera(): Camera
        +getGameObjectWith(Class<T extends Component>): GameObject
        +getGameObjects(): List<GameObject>
        +getGameObject(int): GameObject
        +getGameObject(String): GameObject
        +imgui(): void
        +createGameObject(String): GameObject
        +save(): void
        +load(): void
        +destroy(): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
