@startuml

package javafx.application {
	class Application {}
	}

package java {
    class Main {
        +main(args : String[]) : void
    }
	entity Entity {
		- position: vector
		- inventar: array
		+ interact() : self
		}
	class Game {}
    class GameLoop {
        -isRunning : boolean
        +start(GameWindow gamewindow) : void
        +stop() : void
        +update() : void
        +render() : void
    }
    class GameState {
        -currentState : State
        +changeState(newState : State) : void
    }
	class GameWindow {
		+main() : void
		+start(Stage stage) : void
		}
	class Player extends Entity {}
    class World {
        -tiles : Tile[][]
        +loadWorld() : void
    }
}

package resources {
	class audio {}
	class map_tiles {}
	class map_textures {}
}

package stories {
	+ scene(id : int) : 
}

Main --> Game : new Game
GameWindow --|> Application
Game --> GameWindow : new GameWindow
Game --> GameLoop : start(gamewindow)

@enduml
