@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>Component\n<size:10>game.engine" as game.engine.Component [[Component.html]] {
        +gameObject: GameObject
        +start(): void
        +update(float): void
        +imgui(): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
