@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ImGuiLayer\n<size:10>game.engine" as game.engine.ImGuiLayer [[ImGuiLayer.html]] {
        +ImGuiLayer(long)
        +initImGui(): void
        +update(float, Scene): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
