@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Window\n<size:10>game.engine" as game.engine.Window [[Window.html]] {
        +r: float
        +g: float
        +b: float
        +a: float
        {static} +get(): Window
        {static} +changeScene(SceneInitializer): void
        {static} +getWidth(): int
        {static} +getHeight(): int
        {static} +setWidth(int): void
        {static} +setHeight(int): void
        {static} +getWindow(): Window
        {static} +setWindow(Window): void
        {static} +getScene(): Scene
        {static} +setCurrenScene(Scene): void
        +run(): void
        +init(): void
        +loop(): void
        +getTitle(): String
        +getGlfwWindow(): long
        +isFadeToBlack(): boolean
        +setFadeToBlack(boolean): void
        {static} +getImguiLayer(): ImGuiLayer
        +setImguiLayer(ImGuiLayer): void
        {static} +getFramebuffer(): Framebuffer
        {static} +getCurrenScene(): Scene
        {static} +getTargetAspectRatio(): float
        {static} +getCurrentTime(): float
        +onNotify(GameObject, Event): void
    }

    interface "<size:14>Observer\n<size:10>game.observers" as game.observers.Observer [[../observers/Observer.html]] {
        {abstract} +onNotify(GameObject, Event): void
    }

    game.observers.Observer <|.. game.engine.Window

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
