@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MenuBar\n<size:10>game.editor" as game.editor.MenuBar [[MenuBar.html]] {
        +imgui(): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
