@startuml
    namespace game.editor {

        class JImGui [[JImGui.html]] {
            {static} +drawVec2Control(String, Vector2f): void
            {static} +drawVec2Control(String, Vector2f, float): void
            {static} +drawVec2Control(String, Vector2f, float, float): void
            {static} +drawVec3Control(String, Vector3f): void
            {static} +drawVec3Control(String, Vector3f, float): void
            {static} +drawVec3Control(String, Vector3f, float, float): void
            {static} +dragFloat(String, float): float
            {static} +dragInt(String, int): int
            {static} +colorPicker4(String, Vector4f): boolean
            {static} +inputText(String, String): String
        }

        class MenuBar [[MenuBar.html]] {
            +imgui(): void
        }

        class PropertiesWindow [[PropertiesWindow.html]] {
            +PropertiesWindow(PickingTexture)
            +imgui(): void
            +setActiveGameObject(GameObject): void
            +getActiveGameObject(): GameObject
            +setInactive(): void
            +getActiveGameObjects(): List<GameObject>
            +clearSelected(): void
            +addActiveGameObjet(GameObject): void
            +getPickingTexture(): PickingTexture
        }

        class GameViewWindow [[GameViewWindow.html]] {
            +imgui(): void
            +getWantCaptureMouse(): boolean
        }

        class SceneHeirarchyWindow [[SceneHeirarchyWindow.html]] {
            +imgui(): void
        }

    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
