@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PropertiesWindow\n<size:10>game.editor" as game.editor.PropertiesWindow [[PropertiesWindow.html]] {
        +PropertiesWindow(PickingTexture)
        +update(float, Scene): void
        +imgui(): void
        +setActiveGameObject(int): void
        +getActiveGameObject(): GameObject
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
