@startuml
    namespace game.util {

        class AssetPool [[AssetPool.html]] {
            {static} +getShader(String): Shader
            {static} +getTexture(String): Texture
            {static} +addSpritesheet(String, Spritesheet): void
            {static} +getSpritesheet(String): Spritesheet
        }

        class Settings [[Settings.html]] {
            {static} +RELEASE_BUILD: boolean
            {static} +tileSize: float
            {static} +GRID_WIDTH: float
            {static} +GRID_HEIGHT: float
            {static} +PROJECTION_HEIGHT: float
        }

    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
