@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Settings\n<size:10>game.util" as game.util.Settings [[Settings.html]] {
        {static} +HOME_PATH: String
        {static} +RELEASE_BUILD: boolean
        {static} +tileSize: float
        {static} +GRID_WIDTH: float
        {static} +GRID_HEIGHT: float
        {static} +PROJECTION_HEIGHT: float
        {static} +DEBUG_DRAW: int
        {static} +LEVEL_JSON_PATH: String
        {static} +IMGUI_CONFIG_FILE_PATH: String
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
