@startuml
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    game.renderer --> org.joml
    game.renderer --> game.engine
    game.renderer --> game.components
    game.util --> game.renderer
    game.util --> game.components
    game.components --> org.joml
    game.components --> game.engine
    game.components --> game.renderer
    game.components --> game.editor
    game.components --> com.google.gson
    game.scene --> game.components
    game.scene --> game.engine
    game.scene --> game.renderer
    game.engine --> org.joml
    game.engine --> game.renderer
    game.engine --> game.scene
    game.engine --> game.components
    game.engine --> imgui.gl3
    game.engine --> imgui.glfw
    game.engine --> game.editor
    game.engine --> com.google.gson
    game.editor --> org.joml
    game.editor --> game.engine
    game.editor --> game.renderer
    game.editor --> game.scene
    game.editor --> imgui

    ' Package links
    class "game.renderer" [[game/renderer/package-summary.html]] {
    }
    class "game.engine" [[game/engine/package-summary.html]] {
    }
    class "game.components" [[game/components/package-summary.html]] {
    }
    class "game.util" [[game/util/package-summary.html]] {
    }
    class "game.editor" [[game/editor/package-summary.html]] {
    }
    class "game.scene" [[game/scene/package-summary.html]] {
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
