@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Observer\n<size:10>game.observers" as game.observers.Observer [[Observer.html]] {
        {abstract} +onNotify(GameObject, Event): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
