@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>grow_in_size\n<size:10>game.components.interactives" as game.components.interactives.grow_in_size [[grow_in_size.html]] {
        +interact(GameObject): void
    }

    abstract class "<size:14>Interaktive\n<size:10>game.components" as game.components.Interaktive [[../Interaktive.html]] {
        {abstract} +interact(GameObject): void
    }

    game.components.Interaktive <|-- game.components.interactives.grow_in_size

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
