@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>EventType\n<size:10>game.observers.events" as game.observers.events.EventType [[EventType.html]] {
        {static} +GameEngineStartPlay
        {static} +GameEngineStopPlay
        {static} +SaveLevel
        {static} +LoadLevel
        {static} +UserEvent
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
